using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using Malco.Configuration.Models;

namespace Malco.Localization
{
    internal static class UiText
    {
        private static readonly Dictionary<string, string> Korean = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "Malco", "말코" },
            { "Settings", "설정" },
            { "Features", "기능" },
            { "Layout", "레이아웃" },
            { "Content", "표시 항목" },
            { "Content & Alerts", "표시 항목 및 알림" },
            { "Return to Game", "게임으로 돌아가기" },
            { "Return to game and close overlay settings", "게임으로 돌아가고 말코 설정 닫기" },
            { "Malco settings", "말코 설정" },
            { "HUD settings", "HUD 설정" },
            { "Arrange HUD", "HUD 배치" },
            { "Hide HUD", "HUD 숨기기" },
            { "Show HUD again", "HUD 다시 표시" },
            { "Hide the entire HUD for this session. It is shown again after Malco restarts.", "이번 실행 동안 HUD 전체를 숨깁니다. 말코를 다시 실행하면 자동으로 표시됩니다." },
            { "Show the HUD again. Your saved settings are unchanged.", "HUD를 다시 표시합니다. 저장된 설정은 바뀌지 않습니다." },
            { "HUD temporarily hidden", "HUD 일시 숨김" },
            { "HUD visible", "HUD 표시 중" },
            { "Arrange on screen", "화면에서 위치 조정" },
            { "General", "일반" },
            { "Preferences", "환경 설정" },
            { "Language and app-wide preferences.", "언어와 앱 전체 환경을 설정합니다." },
            { "Program version", "프로그램 버전" },
            { "On", "켜짐" },
            { "Off", "꺼짐" },
            { "Done", "완료" },
            { "Reset panel", "선택 초기화" },
            { "Move toolbar", "도구 모음 이동" },
            { "Drag or use arrow keys to move the toolbar.", "끌거나 방향키를 사용해 도구 모음을 이동하세요." },
            { "Reset all", "전체 초기화" },
            { "Confirm reset", "초기화 확인" },
            { "Cancel", "취소" },
            { "Reset every HUD panel to its default position and size?", "모든 HUD 패널의 위치와 크기를 기본값으로 되돌릴까요?" },
            { "Press again within six seconds.", "6초 안에 한 번 더 누르세요." },
            { "Select a HUD panel", "HUD 패널을 선택하세요" },
            { "Hidden in game", "게임에서 숨김" },
            { "Choose what Malco shows during a match.", "게임 중 말코에 표시할 기능을 선택합니다." },
            { "Changes save automatically", "변경 사항은 자동으로 저장됩니다" },
            { "Saved", "저장됨" },
            { "Selected", "선택됨" },
            { "Not selected", "선택되지 않음" },
            { "settings tab", "설정 탭" },
            { "Saving...", "저장 중..." },
            { "Save failed", "저장 실패" },
            { "Recovery required", "복구 필요" },
            { "Recovered", "복구됨" },
            { "Save failed - settings remain open", "저장 실패 - 설정 창을 유지합니다" },
            { "Retry save", "다시 저장" },
            { "Check the settings file permissions, then retry.", "설정 파일 권한을 확인한 다음 다시 저장하세요." },
            { "Check the settings location, permissions, and available disk space, then retry.", "설정 파일 위치, 권한, 사용 가능한 디스크 공간을 확인한 다음 다시 저장하세요." },
            { "Back up, move or rename hud-layout.json, then retry save.", "hud-layout.json을 백업한 뒤 이동하거나 이름을 바꾸고 다시 저장하세요." },
            { "Application/provider shutdown is blocked.", "애플리케이션 또는 공급자 종료가 차단되었습니다." },
            { "Race", "종족" },
            { "Search items", "항목 검색" },
            { "results", "개 결과" },
            { "Preview", "미리보기" },
            { "Blocked preview", "사용 불가 미리보기" },
            { "layout preview frame", "레이아웃 미리보기 프레임" },
            { "hidden in gameplay", "게임 중 숨김" },
            { "HUD widget", "HUD 위젯" },
            { "Hidden in gameplay", "게임 중 숨김" },
            { "Editable", "편집 가능" },
            { "layout frame", "레이아웃 프레임" },
            { "Drag directly to move. Drag the corner to resize. Click to focus for Arrow and Shift plus Arrow adjustments.", "직접 끌어 이동하고 모서리를 끌어 크기를 조절하세요. 클릭한 뒤 방향키로 이동하고 Shift+방향키로 크기를 조절할 수 있습니다." },
            { "Drag to move this frame. Arrow keys move; Shift plus Arrow resizes.", "끌어서 프레임을 이동하세요. 방향키로 이동하고 Shift+방향키로 크기를 조절합니다." },
            { "Recovery required; writes blocked", "복구 필요, 저장 차단됨" },
            { "Settings recovered", "설정 복구됨" },
            { "Show in game", "게임에 표시" },
            { "Visible", "표시" },
            { "Show in HUD", "HUD에 표시" },
            { "Show building", "건물 표시" },
            { "Alert when available", "사용 가능할 때 알림" },
            { "Warn before completion", "완료 전 알림" },
            { "Search", "검색" },
            { "Clear", "지우기" },
            { "Clear search", "검색 지우기" },
            { "No matching items.", "검색 결과가 없습니다." },
            { "This feature has no additional settings.", "이 기능에는 추가 설정이 없습니다." },
            { "All", "전체" },
            { "All off", "모두 끄기" },
            { "All on", "모두 켜기" },
            { "Buildings", "건물" },
            { "Units", "유닛" },
            { "Upgrades", "업그레이드" },
            { "Research", "연구" },
            { "Status", "상태" },
            { "Alerts", "알림" },
            { "Guides", "가이드" },
            { "Partially on", "일부 켜짐" },
            { "Worker count", "일꾼 수" },
            { "Idle and total worker counts.", "쉬는 일꾼과 전체 일꾼 수를 표시합니다." },
            { "Worker count style", "일꾼 수 표시 스타일" },
            { "Choose how worker counts are displayed.", "일꾼 수의 표시 스타일을 선택합니다." },
            { "Classic green", "클래식 녹색" },
            { "White", "흰색" },
            { "Unit counts", "유닛 수" },
            { "Combat-unit icons with current counts.", "보유 중인 전투 유닛 수를 표시합니다." },
            { "Building counts", "건물 수" },
            { "Owned building icons with current counts.", "보유 중인 건물 수를 표시합니다." },
            { "Completed upgrades", "완료된 업그레이드" },
            { "Completed upgrades, levels, and researched abilities.", "완료한 업그레이드와 연구를 표시합니다." },
            { "Ready to research", "연구 가능" },
            { "Upgrades and abilities you can start now.", "지금 시작할 수 있는 업그레이드와 연구를 표시합니다." },
            { "Completion display", "완료 예정 표시" },
            { "Completion display mode", "완료 표시 방식" },
            { "Choose how active upgrades and research show progress.", "진행 중인 업그레이드와 연구의 진행 상황 표시 방식을 선택합니다." },
            { "Icon size", "아이콘 크기" },
            { "Choose the icon size for this display.", "이 표시의 아이콘 크기를 선택합니다." },
            { "Small", "작게" },
            { "Medium", "보통" },
            { "Large", "크게" },
            { "Displayed content", "표시 항목" },
            { "Availability alerts", "사용 가능 알림" },
            { "Completion alerts", "완료 알림" },
            { "Command lines", "명령 경로" },
            { "Current and queued command paths for selected units.", "선택한 유닛의 현재 및 예약 명령 경로를 표시합니다." },
            { "Current and queued command paths for selected units, plus active targets for selected defensive buildings.", "선택한 유닛의 현재 및 예약 명령 경로와 선택한 방어 건물의 현재 공격 대상을 표시합니다." },
            { "Rally lines", "랠리 경로" },
            { "Rally paths for selected production buildings.", "선택한 생산 건물의 랠리 경로를 표시합니다." },
            { "Minerals", "미네랄" },
            { "Mineral worker counts by base.", "기지별 미네랄 일꾼 수를 표시합니다." },
            { "Gas", "가스" },
            { "Gas worker counts by refinery.", "가스 건물별 배치된 일꾼 수를 표시합니다." },
            { "Resource workers", "자원 및 일꾼 표시" },
            { "Choose which resource worker counts appear on the map.", "맵에 표시할 자원별 일꾼 수를 선택합니다." },
            { "Transport cargo", "수송선 내부 표시" },
            { "Show or hide passenger icons and counts inside loaded transports.", "탑승 중인 수송선 내부에 유닛 아이콘과 수를 표시할지 선택합니다." },
            { "Passenger icons and counts", "탑승 유닛 아이콘 및 숫자" },
            { "Show passenger unit icons and counts inside loaded transports.", "탑승 중인 수송선 안에 유닛 아이콘과 숫자를 표시합니다." },
            { "Ability indicators", "스킬 사용 표시" },
            { "Choose energy or a ready-skill dot for each ability-capable unit or building.", "스킬 사용이 가능한 유닛과 건물별로 마나 숫자 또는 사용 가능한 스킬의 빨간 점 표시를 선택합니다." },
            { "Ability indicator", "스킬 표시" },
            { "Energy number", "마나 숫자" },
            { "Skill", "스킬" },
            { "Hidden", "미표시" },
            { "Per unit", "유닛별 설정" },
            { "Countdown", "카운트다운" },
            { "Countdown duration", "카운트다운 시간" },
            { "Choose when the completion countdown appears (5-30 seconds).", "완료 카운트다운을 몇 초 전부터 표시할지 선택합니다(5~30초)." },
            { "Decrease countdown duration", "카운트다운 시간 줄이기" },
            { "Increase countdown duration", "카운트다운 시간 늘리기" },
            { "{0} seconds", "{0}초" },
            { "Full progress", "전체 진행률" },
            { "Language", "언어" },
            { "English", "영어" },
            { "Korean", "한국어" },
            { "2 idle", "대기 2" },
            { "24 total", "전체 24" },
            { "No units", "유닛 없음" },
            { "Producing", "생산 중" },
            { "No buildings", "건물 없음" },
            { "No upgrades or tech", "완료된 업그레이드 또는 연구 없음" },
            { "Blocked", "사용 불가" },
            { "Available", "사용 가능" },
            { "Filter buildings, units, upgrades, and research", "건물, 유닛, 업그레이드 및 연구 검색" },
            { "Choose individual HUD items and research alerts.", "HUD에 표시할 개별 항목과 연구 알림을 선택합니다." },
            { "Global and item settings", "전체 기능과 개별 항목 설정" },
            { "Whole HUD panels are controlled in Features. Controls below affect only the named building or item; alerts do not change HUD visibility.", "전체 HUD 패널은 기능 탭에서 켜고 끕니다. 아래 설정은 해당 건물이나 항목에만 적용되며, 알림 설정은 HUD 표시 여부를 바꾸지 않습니다." },
            { "Global panel visibility and individual item ownership", "전체 패널 표시와 개별 항목 설정의 범위" },
            { "building group", "건물 그룹" },
            { "This control changes only this building or item; it does not show or hide the whole HUD panel.", "이 설정은 해당 건물이나 항목만 변경하며 전체 HUD 패널을 켜거나 끄지 않습니다." },
            { "Alert when this upgrade or research can be started.", "이 업그레이드나 연구를 시작할 수 있을 때 알립니다." },
            { "Show a countdown shortly before this upgrade or research completes.", "이 업그레이드나 연구가 완료되기 직전에 알립니다." },
            { "Show the selected completion display for this upgrade or research.", "이 업그레이드나 연구에 선택한 완료 표시 방식을 적용합니다." },
            { "Building", "건물" },
            { "Unit", "유닛" },
            { "Upgrade", "업그레이드" },
            { "Tech", "연구" },
            { "Item", "항목" },
            { "Building visibility applies only to this building; item rows have independent settings.", "건물 표시 설정은 이 건물에만 적용되며 하위 항목은 각각 별도로 설정합니다." },
            { "This row changes only this item.", "이 행은 해당 항목만 변경합니다." },
            { "Controls whether this panel appears during gameplay. Layout previews remain editable while hidden.", "게임 중 이 패널을 표시할지 설정합니다. 숨긴 상태에서도 레이아웃 미리보기는 편집할 수 있습니다." },
            { "icon", "아이콘" },
            { "Choose race", "종족 선택" },
            { "Terran", "테란" },
            { "Zerg", "저그" },
            { "Protoss", "프로토스" },
            { "Hidden globally — item preferences are preserved.", "전체 기능은 꺼져 있지만 항목 설정은 유지됩니다." },
            { "Settings could not be saved.", "설정을 저장하지 못했습니다." },
            { "Quit Malco", "말코 종료" },
            { "Quit Malco? The game will keep running.", "말코를 종료할까요? 게임은 계속 실행됩니다." },
            { "hotkey unavailable", "단축키 사용 불가" },
            { "shutdown blocked", "종료 차단됨" },
            { "Retry Quit", "종료 다시 시도" },
            { "Hotkey unavailable - use Settings", "단축키를 사용할 수 없음 - 설정을 사용하세요" },
            { "Window event fallback active", "창 이벤트 대체 모드 사용 중" },
            { "Drag a panel preview to move it. Drag its corner to resize. Arrow keys move; Shift+Arrow resizes.", "패널 미리보기를 끌어 이동하고 모서리를 끌어 크기를 조절합니다. 방향키로 이동하고 Shift+방향키로 크기를 조절합니다." },
            { "Overlay panels", "오버레이 패널" },
            { "On-map indicators (position follows game units)", "맵 위 안내선 (게임 유닛 위치를 따라감)" },
            { "Position follows game units", "게임 유닛 위치를 따라감" },
            { "Drag its preview to move or resize", "미리보기를 끌어 이동하거나 크기 조절" },
            { "Workers", "일꾼" },
            { "Completed upgrades and research", "완료된 업그레이드 및 연구" },
            { "Upgrade completion", "업그레이드 완료" },
            { "Building rally lines", "건물 랠리 경로" },
            { "Unit command lines", "유닛 명령 경로" },
            { "Movable and resizable idle and total worker counts.", "이동하고 크기를 조절할 수 있는 쉬는 일꾼과 전체 일꾼 수 표시입니다." },
            { "Completed upgrades and researched abilities.", "완료한 업그레이드와 연구를 표시합니다." },
            { "Upgrades and abilities that can be started now.", "지금 시작할 수 있는 업그레이드와 연구를 표시합니다." },
            { "Upgrades and abilities you can start now; blocked options are dimmed.", "지금 시작할 수 있는 업그레이드와 연구를 표시하며 사용할 수 없는 항목은 흐리게 표시합니다." },
            { "Research available", "연구 가능" },
            { "Upcoming research completion", "완료 예정 연구" },
            { "Show a configurable countdown or full progress.", "설정한 카운트다운 또는 전체 진행률을 표시합니다." },
            { "Command paths", "명령 경로" },
            { "Rally paths", "랠리 경로" },
            { "Resource worker indicators", "자원 일꾼 표시" },
            { "Transport cargo display", "수송선 내부 표시" },
            { "Ability readiness display", "스킬 사용 표시" }
        };

        private static readonly Dictionary<string, string> KoreanGameTerms = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Marine", "마린" }, { "Ghost", "고스트" }, { "Vulture", "벌처" }, { "Goliath", "골리앗" },
            { "Siege Tank", "시즈 탱크" }, { "SCV", "SCV" }, { "Wraith", "레이스" }, { "Science Vessel", "사이언스 베슬" },
            { "Dropship", "드랍십" }, { "Battlecruiser", "배틀크루저" }, { "Firebat", "파이어뱃" }, { "Medic", "메딕" },
            { "Zergling", "저글링" }, { "Hydralisk", "히드라리스크" }, { "Ultralisk", "울트라리스크" }, { "Broodling", "브루들링" },
            { "Drone", "드론" }, { "Overlord", "오버로드" }, { "Mutalisk", "뮤탈리스크" }, { "Guardian", "가디언" },
            { "Queen", "퀸" }, { "Defiler", "디파일러" }, { "Scourge", "스커지" }, { "Infested Terran", "감염된 테란" },
            { "Valkyrie", "발키리" }, { "Corsair", "커세어" }, { "Dark Templar", "다크 템플러" }, { "Devourer", "디바우러" },
            { "Probe", "프로브" }, { "Zealot", "질럿" }, { "Dragoon", "드라군" }, { "High Templar", "하이 템플러" },
            { "Shuttle", "셔틀" }, { "Scout", "스카웃" }, { "Arbiter", "아비터" }, { "Carrier", "캐리어" },
            { "Reaver", "리버" }, { "Observer", "옵저버" }, { "Lurker", "럴커" },
            { "Command Center", "커맨드 센터" }, { "Comsat Station", "컴샛 스테이션" }, { "Nuclear Silo", "뉴클리어 사일로" },
            { "Supply Depot", "서플라이 디포" }, { "Refinery", "리파이너리" }, { "Barracks", "배럭" }, { "Academy", "아카데미" },
            { "Factory", "팩토리" }, { "Starport", "스타포트" }, { "Control Tower", "컨트롤 타워" },
            { "Science Facility", "사이언스 퍼실리티" }, { "Covert Ops", "코버트 옵스" }, { "Physics Lab", "피직스 랩" },
            { "Machine Shop", "머신샵" }, { "Engineering Bay", "엔지니어링 베이" }, { "Armory", "아머리" },
            { "Missile Turret", "미사일 터렛" }, { "Bunker", "벙커" }, { "Infested Command Center", "감염된 커맨드 센터" },
            { "Hatchery", "해처리" }, { "Lair", "레어" }, { "Hive", "하이브" }, { "Nydus Canal", "나이더스 커널" },
            { "Hydralisk Den", "히드라리스크 덴" }, { "Defiler Mound", "디파일러 마운드" }, { "Greater Spire", "그레이터 스파이어" },
            { "Queen's Nest", "퀸즈 네스트" }, { "Evolution Chamber", "에볼루션 챔버" }, { "Ultralisk Cavern", "울트라리스크 캐번" },
            { "Spire", "스파이어" }, { "Spawning Pool", "스포닝 풀" }, { "Creep Colony", "크립 콜로니" },
            { "Spore Colony", "스포어 콜로니" }, { "Sunken Colony", "성큰 콜로니" }, { "Extractor", "익스트랙터" },
            { "Nexus", "넥서스" }, { "Robotics Facility", "로보틱스 퍼실리티" }, { "Pylon", "파일런" },
            { "Assimilator", "어시밀레이터" }, { "Observatory", "옵저버토리" }, { "Gateway", "게이트웨이" },
            { "Photon Cannon", "포톤 캐논" }, { "Citadel of Adun", "시타델 오브 아둔" }, { "Cybernetics Core", "사이버네틱스 코어" },
            { "Templar Archives", "템플러 아카이브" }, { "Forge", "포지" }, { "Stargate", "스타게이트" },
            { "Fleet Beacon", "플릿 비콘" }, { "Arbiter Tribunal", "아비터 트리뷰널" },
            { "Robotics Support Bay", "로보틱스 서포트 베이" }, { "Shield Battery", "실드 배터리" },
            { "Terran Infantry Armor", "보병 방어력" }, { "Terran Infantry Weapons", "보병 공격력" },
            { "Terran Vehicle Plating", "차량 방어력" }, { "Terran Vehicle Weapons", "차량 공격력" },
            { "Terran Ship Plating", "함선 방어력" }, { "Terran Ship Weapons", "함선 공격력" },
            { "Zerg Carapace", "갑피" }, { "Zerg Melee Attacks", "근접 공격력" }, { "Zerg Missile Attacks", "미사일 공격력" },
            { "Zerg Flyer Carapace", "비행체 갑피" }, { "Zerg Flyer Attacks", "비행체 공격력" },
            { "Protoss Ground Armor", "지상 방어력" }, { "Protoss Ground Weapons", "지상 공격력" },
            { "Protoss Air Armor", "공중 방어력" }, { "Protoss Air Weapons", "공중 공격력" },
            { "Protoss Plasma Shields", "플라즈마 실드" }, { "Stim Packs", "스팀 팩" }, { "Tank Siege Mode", "시즈 모드" },
            { "Spider Mines", "스파이더 마인" }, { "Cloaking Field", "클로킹 필드" }, { "Personnel Cloaking", "퍼스널 클로킹" },
            { "EMP Shockwave", "EMP 쇼크웨이브" }, { "Irradiate", "이레디에이트" }, { "Yamato Gun", "야마토 포" },
            { "Burrowing", "버로우" }, { "Spawn Broodlings", "브루들링 생성" }, { "Dark Swarm", "다크 스웜" },
            { "Plague", "플레이그" }, { "Consume", "컨슘" }, { "Ensnare", "인스네어" }, { "Parasite", "패러사이트" },
            { "Psionic Storm", "사이오닉 스톰" }, { "Hallucination", "할루시네이션" }, { "Recall", "리콜" },
            { "Stasis Field", "스테이시스 필드" }, { "Restoration", "리스토레이션" }, { "Disruption Web", "디스럽션 웹" },
            { "Mind Control", "마인드 컨트롤" }, { "Optical Flare", "옵티컬 플레어" }, { "Maelstrom", "메일스트롬" },
            { "Lurker Aspect", "럴커 변태" }, { "Carrier Capacity", "캐리어 수용력" }, { "Reaver Capacity", "리버 수용력" },
            { "Scarab Damage", "스캐럽 공격력" }, { "Singularity Charge", "싱귤래리티 차지" }, { "Leg Enhancements", "다리 강화" },
            { "Adrenal Glands", "아드레날 글랜드" }, { "Anabolic Synthesis", "아나볼릭 신서시스" },
            { "Antennae", "안테나" }, { "Apial Sensors", "에이피얼 센서" }, { "Apollo Reactor", "아폴로 리액터" },
            { "Argus Jewel", "아르거스 쥬얼" }, { "Argus Talisman", "아르거스 탈리스만" },
            { "Caduceus Reactor", "카두세우스 리액터" }, { "Charon Boosters", "카론 부스터" },
            { "Chitinous Plating", "키틴질 장갑" }, { "Colossus Reactor", "콜로서스 리액터" },
            { "Gamete Meiosis", "가메테 마이오시스" }, { "Gravitic Boosters", "그래비틱 부스터" },
            { "Gravitic Drive", "그래비틱 드라이브" }, { "Gravitic Thrusters", "그래비틱 스러스터" },
            { "Grooved Spines", "그루브드 스파인" }, { "Ion Thrusters", "이온 스러스터" },
            { "Khaydarin Amulet", "케이다린 아뮬렛" }, { "Khaydarin Core", "케이다린 코어" },
            { "Lockdown", "락다운" }, { "Metabolic Boost", "메타볼릭 부스트" },
            { "Metasynaptic Node", "메타시냅틱 노드" }, { "Moebius Reactor", "뫼비우스 리액터" },
            { "Muscular Augments", "머스큘러 어그먼트" }, { "Ocular Implants", "오큘러 임플란트" },
            { "Pneumatized Carapace", "기낭 갑피" }, { "Sensor Array", "센서 어레이" },
            { "Titan Reactor", "타이탄 리액터" }, { "U 238 Shells", "U-238 탄환" },
            { "Ventral Sacs", "복부 주머니" }
        };

        public static string CurrentLanguage { get; private set; } = MalcoPreferenceValues.English;

        public static void Initialize(string language)
        {
            CurrentLanguage = MalcoPreferenceValues.NormalizeLanguage(language);
            var culture = CultureInfo.GetCultureInfo(
                string.Equals(CurrentLanguage, MalcoPreferenceValues.Korean, StringComparison.Ordinal)
                    ? "ko-KR"
                    : "en-US");
            Thread.CurrentThread.CurrentUICulture = culture;
        }

        public static string Get(string english)
        {
            if (!string.Equals(CurrentLanguage, MalcoPreferenceValues.Korean, StringComparison.Ordinal))
            {
                return english ?? string.Empty;
            }

            string translated;
            return english != null && Korean.TryGetValue(english, out translated) ? translated : english ?? string.Empty;
        }

        public static string GameName(string english)
        {
            var normalized = (english ?? string.Empty).Replace('_', ' ');
            if (!string.Equals(CurrentLanguage, MalcoPreferenceValues.Korean, StringComparison.Ordinal))
            {
                return normalized;
            }

            string translated;
            return KoreanGameTerms.TryGetValue(normalized, out translated) ? translated : normalized;
        }
    }
}
